export const validCountries = [
  { name: "Afghanistan", continent: "Asia" },
  { name: "Åland Islands", continent: "Europe" },
  { name: "Albania", continent: "Europe" },
  { name: "Algeria", continent: "Africa" },
  { name: "American Samoa", continent: "Oceania" },
  { name: "Andorra", continent: "Europe" },
  { name: "Angola", continent: "Africa" },
  { name: "Anguilla", continent: "Americas" },
  { name: "Antarctica", continent: "Antarctic" },
  { name: "Antigua and Barbuda", continent: "Americas" },
  { name: "Argentina", continent: "Americas" },
  { name: "Armenia", continent: "Asia" },
  { name: "Aruba", continent: "Americas" },
  { name: "Australia", continent: "Oceania" },
  { name: "Austria", continent: "Europe" },
  { name: "Azerbaijan", continent: "Asia" },
  { name: "Bahamas", continent: "Americas" },
  { name: "Bahrain", continent: "Asia" },
  { name: "Bangladesh", continent: "Asia" },
  { name: "Barbados", continent: "Americas" },
  { name: "Belarus", continent: "Europe" },
  { name: "Belgium", continent: "Europe" },
  { name: "Belize", continent: "Americas" },
  { name: "Benin", continent: "Africa" },
  { name: "Bermuda", continent: "Americas" },
  { name: "Bhutan", continent: "Asia" },
  { name: "Bolivia", continent: "Americas" },
  { name: "Bosnia and Herzegovina", continent: "Europe" },
  { name: "Botswana", continent: "Africa" },
  { name: "Bouvet Island", continent: "Antarctic" },
  { name: "Brazil", continent: "Americas" },
  { name: "British Indian Ocean Territory", continent: "Africa" },
  { name: "British Virgin Islands", continent: "Americas" },
  { name: "Brunei", continent: "Asia" },
  { name: "Bulgaria", continent: "Europe" },
  { name: "Burkina Faso", continent: "Africa" },
  { name: "Burundi", continent: "Africa" },
  { name: "Cambodia", continent: "Asia" },
  { name: "Cameroon", continent: "Africa" },
  { name: "Canada", continent: "Americas" },
  { name: "Cape Verde", continent: "Africa" },
  { name: "Caribbean Netherlands", continent: "Americas" },
  { name: "Cayman Islands", continent: "Americas" },
  { name: "Central African Republic", continent: "Africa" },
  { name: "Chad", continent: "Africa" },
  { name: "Chile", continent: "Americas" },
  { name: "China", continent: "Asia" },
  { name: "Christmas Island", continent: "Oceania" },
  { name: "Cocos (Keeling) Islands", continent: "Oceania" },
  { name: "Colombia", continent: "Americas" },
  { name: "Comoros", continent: "Africa" },
  { name: "Cook Islands", continent: "Oceania" },
  { name: "Costa Rica", continent: "Americas" },
  { name: "Croatia", continent: "Europe" },
  { name: "Cuba", continent: "Americas" },
  { name: "Curaçao", continent: "Americas" },
  { name: "Cyprus", continent: "Europe" },
  { name: "Czechia", continent: "Europe" },
  { name: "Denmark", continent: "Europe" },
  { name: "Djibouti", continent: "Africa" },
  { name: "Dominica", continent: "Americas" },
  { name: "Dominican Republic", continent: "Americas" },
  { name: "DR Congo", continent: "Africa" },
  { name: "Ecuador", continent: "Americas" },
  { name: "Egypt", continent: "Africa" },
  { name: "El Salvador", continent: "Americas" },
  { name: "Equatorial Guinea", continent: "Africa" },
  { name: "Eritrea", continent: "Africa" },
  { name: "Estonia", continent: "Europe" },
  { name: "Eswatini", continent: "Africa" },
  { name: "Ethiopia", continent: "Africa" },
  { name: "Falkland Islands", continent: "Americas" },
  { name: "Faroe Islands", continent: "Europe" },
  { name: "Fiji", continent: "Oceania" },
  { name: "Finland", continent: "Europe" },
  { name: "France", continent: "Europe" },
  { name: "French Guiana", continent: "Americas" },
  { name: "French Polynesia", continent: "Oceania" },
  { name: "French Southern and Antarctic Lands", continent: "Antarctic" },
  { name: "Gabon", continent: "Africa" },
  { name: "Gambia", continent: "Africa" },
  { name: "Georgia", continent: "Asia" },
  { name: "Germany", continent: "Europe" },
  { name: "Ghana", continent: "Africa" },
  { name: "Gibraltar", continent: "Europe" },
  { name: "Greece", continent: "Europe" },
  { name: "Greenland", continent: "Americas" },
  { name: "Grenada", continent: "Americas" },
  { name: "Guadeloupe", continent: "Americas" },
  { name: "Guam", continent: "Oceania" },
  { name: "Guatemala", continent: "Americas" },
  { name: "Guernsey", continent: "Europe" },
  { name: "Guinea", continent: "Africa" },
  { name: "Guinea-Bissau", continent: "Africa" },
  { name: "Guyana", continent: "Americas" },
  { name: "Haiti", continent: "Americas" },
  { name: "Heard Island and McDonald Islands", continent: "Antarctic" },
  { name: "Honduras", continent: "Americas" },
  { name: "Hong Kong", continent: "Asia" },
  { name: "Hungary", continent: "Europe" },
  { name: "Iceland", continent: "Europe" },
  { name: "India", continent: "Asia" },
  { name: "Indonesia", continent: "Asia" },
  { name: "Iran", continent: "Asia" },
  { name: "Iraq", continent: "Asia" },
  { name: "Ireland", continent: "Europe" },
  { name: "Isle of Man", continent: "Europe" },
  { name: "Israel", continent: "Asia" },
  { name: "Italy", continent: "Europe" },
  { name: "Ivory Coast", continent: "Africa" },
  { name: "Jamaica", continent: "Americas" },
  { name: "Japan", continent: "Asia" },
  { name: "Jersey", continent: "Europe" },
  { name: "Jordan", continent: "Asia" },
  { name: "Kazakhstan", continent: "Asia" },
  { name: "Kenya", continent: "Africa" },
  { name: "Kiribati", continent: "Oceania" },
  { name: "Kosovo", continent: "Europe" },
  { name: "Kuwait", continent: "Asia" },
  { name: "Kyrgyzstan", continent: "Asia" },
  { name: "Laos", continent: "Asia" },
  { name: "Latvia", continent: "Europe" },
  { name: "Lebanon", continent: "Asia" },
  { name: "Lesotho", continent: "Africa" },
  { name: "Liberia", continent: "Africa" },
  { name: "Libya", continent: "Africa" },
  { name: "Liechtenstein", continent: "Europe" },
  { name: "Lithuania", continent: "Europe" },
  { name: "Luxembourg", continent: "Europe" },
  { name: "Macau", continent: "Asia" },
  { name: "Madagascar", continent: "Africa" },
  { name: "Malawi", continent: "Africa" },
  { name: "Malaysia", continent: "Asia" },
  { name: "Maldives", continent: "Asia" },
  { name: "Mali", continent: "Africa" },
  { name: "Malta", continent: "Europe" },
  { name: "Marshall Islands", continent: "Oceania" },
  { name: "Martinique", continent: "Americas" },
  { name: "Mauritania", continent: "Africa" },
  { name: "Mauritius", continent: "Africa" },
  { name: "Mayotte", continent: "Africa" },
  { name: "Mexico", continent: "Americas" },
  { name: "Micronesia", continent: "Oceania" },
  { name: "Moldova", continent: "Europe" },
  { name: "Monaco", continent: "Europe" },
  { name: "Mongolia", continent: "Asia" },
  { name: "Montenegro", continent: "Europe" },
  { name: "Montserrat", continent: "Americas" },
  { name: "Morocco", continent: "Africa" },
  { name: "Mozambique", continent: "Africa" },
  { name: "Myanmar", continent: "Asia" },
  { name: "Namibia", continent: "Africa" },
  { name: "Nauru", continent: "Oceania" },
  { name: "Nepal", continent: "Asia" },
  { name: "Netherlands", continent: "Europe" },
  { name: "New Caledonia", continent: "Oceania" },
  { name: "New Zealand", continent: "Oceania" },
  { name: "Nicaragua", continent: "Americas" },
  { name: "Niger", continent: "Africa" },
  { name: "Nigeria", continent: "Africa" },
  { name: "Niue", continent: "Oceania" },
  { name: "Norfolk Island", continent: "Oceania" },
  { name: "North Korea", continent: "Asia" },
  { name: "North Macedonia", continent: "Europe" },
  { name: "Northern Mariana Islands", continent: "Oceania" },
  { name: "Norway", continent: "Europe" },
  { name: "Oman", continent: "Asia" },
  { name: "Pakistan", continent: "Asia" },
  { name: "Palau", continent: "Oceania" },
  { name: "Palestine", continent: "Asia" },
  { name: "Panama", continent: "Americas" },
  { name: "Papua New Guinea", continent: "Oceania" },
  { name: "Paraguay", continent: "Americas" },
  { name: "Peru", continent: "Americas" },
  { name: "Philippines", continent: "Asia" },
  { name: "Pitcairn Islands", continent: "Oceania" },
  { name: "Poland", continent: "Europe" },
  { name: "Portugal", continent: "Europe" },
  { name: "Puerto Rico", continent: "Americas" },
  { name: "Qatar", continent: "Asia" },
  { name: "Republic of the Congo", continent: "Africa" },
  { name: "Réunion", continent: "Africa" },
  { name: "Romania", continent: "Europe" },
  { name: "Russia", continent: "Europe" },
  { name: "Rwanda", continent: "Africa" },
  { name: "Saint Barthélemy", continent: "Americas" },
  { name: "Saint Helena, Ascension and Tristan da Cunha", continent: "Africa" },
  { name: "Saint Kitts and Nevis", continent: "Americas" },
  { name: "Saint Lucia", continent: "Americas" },
  { name: "Saint Martin", continent: "Americas" },
  { name: "Saint Pierre and Miquelon", continent: "Americas" },
  { name: "Saint Vincent and the Grenadines", continent: "Americas" },
  { name: "Samoa", continent: "Oceania" },
  { name: "San Marino", continent: "Europe" },
  { name: "São Tomé and Príncipe", continent: "Africa" },
  { name: "Saudi Arabia", continent: "Asia" },
  { name: "Senegal", continent: "Africa" },
  { name: "Serbia", continent: "Europe" },
  { name: "Seychelles", continent: "Africa" },
  { name: "Sierra Leone", continent: "Africa" },
  { name: "Singapore", continent: "Asia" },
  { name: "Sint Maarten", continent: "Americas" },
  { name: "Slovakia", continent: "Europe" },
  { name: "Slovenia", continent: "Europe" },
  { name: "Solomon Islands", continent: "Oceania" },
  { name: "Somalia", continent: "Africa" },
  { name: "South Africa", continent: "Africa" },
  { name: "South Georgia", continent: "Antarctic" },
  { name: "South Korea", continent: "Asia" },
  { name: "South Sudan", continent: "Africa" },
  { name: "Spain", continent: "Europe" },
  { name: "Sri Lanka", continent: "Asia" },
  { name: "Sudan", continent: "Africa" },
  { name: "Suriname", continent: "Americas" },
  { name: "Svalbard and Jan Mayen", continent: "Europe" },
  { name: "Sweden", continent: "Europe" },
  { name: "Switzerland", continent: "Europe" },
  { name: "Syria", continent: "Asia" },
  { name: "Taiwan", continent: "Asia" },
  { name: "Tajikistan", continent: "Asia" },
  { name: "Tanzania", continent: "Africa" },
  { name: "Thailand", continent: "Asia" },
  { name: "Timor-Leste", continent: "Asia" },
  { name: "Togo", continent: "Africa" },
  { name: "Tokelau", continent: "Oceania" },
  { name: "Tonga", continent: "Oceania" },
  { name: "Trinidad and Tobago", continent: "Americas" },
  { name: "Tunisia", continent: "Africa" },
  { name: "Turkey", continent: "Asia" },
  { name: "Turkmenistan", continent: "Asia" },
  { name: "Turks and Caicos Islands", continent: "Americas" },
  { name: "Tuvalu", continent: "Oceania" },
  { name: "Uganda", continent: "Africa" },
  { name: "Ukraine", continent: "Europe" },
  { name: "United Arab Emirates", continent: "Asia" },
  { name: "United Kingdom", continent: "Europe" },
  { name: "United States", continent: "Americas" },
  { name: "United States Minor Outlying Islands", continent: "Americas" },
  { name: "United States Virgin Islands", continent: "Americas" },
  { name: "Uruguay", continent: "Americas" },
  { name: "Uzbekistan", continent: "Asia" },
  { name: "Vanuatu", continent: "Oceania" },
  { name: "Vatican City", continent: "Europe" },
  { name: "Venezuela", continent: "Americas" },
  { name: "Vietnam", continent: "Asia" },
  { name: "Wallis and Futuna", continent: "Oceania" },
  { name: "Western Sahara", continent: "Africa" },
  { name: "Yemen", continent: "Asia" },
  { name: "Zambia", continent: "Africa" },
  { name: "Zimbabwe", continent: "Africa" },
];

export const continents = ['Africa', 'Americas', 'Antartica', 'Asia', 'Europe', 'Oceania'];
